[package]
name = "hkserver"
version = "0.1.0"
authors = ["Shaheen Gandhi <visigoth@gmail.com>"]
edition = "2018"
description = "A gRPC server for HomeKit"

[dependencies]
prost = "0.6.1"
protobuf = "2.18.1"
tokio = "0.3.5"
tonic = "0.3.1"

[build-dependencies]
tonic-build = "0.3.1"
